[package]
name = "rust-gtk4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk4 = { version = "0.6.6", features = [ "v4_6" ] }
lazy_static = "1.4.0"
